unbind r
bind r source-file ~/.config/tmux/tmux.conf
# Set the new prefix to Alt+a (M-a)
set -g prefix M-f

# Set the indexing to 1
set -g base-index 1
set -g mouse on
# using the vim keybinds to navigate
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
