# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = kdeconnect-indicator
exec-once = sleep 2 && /usr/lib/pentablet/pentablet.sh /mini
