# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = kdeconnect-indicator
exec-once = sh -c "sleep 5 && env QT_QPA_PLATFORM=xcb /usr/lib/pentablet/PenTablet.sh /mini"
