# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`


gesture = 4, swipe, move,
gesture = 3, pinch, float
gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, global, quickshell:overviewWorkspacesToggle
gesture = 3, down, dispatcher, global, quickshell:overviewWorkspacesClose
gestures {
    workspace_swipe_distance = 10
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_min_speed_to_force = 2
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true

}


input {
    kb_layout = us,ara
    kb_options = grp:win_space_toggle
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35
    force_no_accel = true
    follow_mouse = 1
    sensitivity = -1
    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 1
        # sensitivity = 0
    }
}

