return {
  -- 1. Syntax Highlighting via Treesitter
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      if type(opts.ensure_installed) == "table" then
        vim.list_extend(opts.ensure_installed, { "arduino", "c", "cpp" })
      end
    end,
  },

  -- 2. Auto-completion and Diagnostics via LSP
  {
    "neovim/nvim-lspconfig",
    opts = {
      -- Ensure Mason automatically downloads these servers
      servers = {
        -- 1. Kotlin Language Server Configuration
        kotlin_language_server = {
          -- If you opted to keep Java 26 system-wide, uncomment the cmd line below 
          -- to force the language server to use your local Java 21 installation:
          -- cmd = { "/usr/lib/jvm/java-21-openjdk/bin/java", "-jar", vim.fn.expand("$HOME/.local/share/nvim/mason/packages/kotlin-language-server/server/lib/kotlin-language-server.jar") },
          
          filetypes = { "kotlin" },
          root_dir = function(fname)
            local util = require("lspconfig.util")
            return util.root_pattern("settings.gradle", "settings.gradle.kts", "build.gradle", "build.gradle.kts", ".git")(fname)
          end,
        },

        -- 2. Arduino Language Server Configuration (for ESP32)
        arduino_language_server = {
          -- The LSP needs to know where your arduino-cli and its config live
          cmd = {
            "arduino-language-server",
            "-cli-config",
            vim.fn.expand("~/.arduino15/arduino-cli.yaml"),
            "-cli",
            "arduino-cli",
            "-clangd",
            "clangd",
          },
          filetypes = { "arduino" },
          root_dir = function(fname)
            local util = require("lspconfig.util")
            -- Crucial: Looks for sketch.yaml generated by 'arduino-cli board attach'
            return util.root_pattern("sketch.yaml", "arduino-cli.yaml", ".git")(fname)
          end,
        },
      },
    },
  },
}
